### ISSUE TITLE
default pred for p_loop()

### ISSUE THREAD

**Issue by adamSales** [manncz/dRCT#10]
In the `p_loop()` function, the helpfile says

> By default, this is `p_rf_interp`

But the code is

```
p_loop = function(Y,Tr,Z=NULL,P,n=NULL,pred = p_simple,returnFitInfo=FALSE,...)
```
so `p_simple` is the default.

I think we should stick with `p_rf_interp` but in any case the helpfile and code need to be consistent.

**Comment by manncz** [comment]
Ah yes, I haven't been careful about the helpfiles. I will go through the `p_loop()` ones next week.

**Comment by manncz** [comment]
986359840becd40dc3e443aaf1d3a3ead11bf01b fixes this!
